### ISSUE TITLE
Execution of run.bat failed due to a Value Error.

### ISSUE THREAD

**Issue by Accelan** [tyapa0/YukariWhisper#1]
Hi, 
I executed run.bat and got an error like the attached image.
It seems that port number settings between NEO-innerAPI and YukariWhisper are match.
Could you please advise me how to solve this?

My environment is below :
- Windows 10 Home
- python 3.11.7
- ゆかこねNEO
- WebSocket port (NEO-innerAPI) 55501/tcp

![2024-01-27 05_09_18-New Issue · tyapa0_YukariWhisper - Vivaldi](https://github.com/tyapa0/YukariWhisper/assets/40535024/3e9da737-f862-4e23-84e3-9128e81254a8)
![2024-01-27 05_14_15-yukariwhisper ini - sakura 2 4 1 2849](https://github.com/tyapa0/YukariWhisper/assets/40535024/748ff645-48ce-453d-be5d-9947f63a18b6)

**Comment by tyapa0** [comment]
※日本語で使うプロジェクトなので日本語で良いと思います

yukariwhisper.iniのwhisper_deviceを以下に書き換えてください

whisper_device = cuda_8_1
もしくは
whisper_device = cuda_16
※こちらの方が動作は確実ですがGPUメモリ消費が少し多くなります

解説：
　上記エラーはポートではなくwhisperのパラメータ指定のエラーです。
　自動的に動作するものが選択されるはずですが、ドライバの機嫌によっては上手く動いていない様です。
　次回更新でint8_float16を標準とする予定です。

**Comment by Accelan** [comment]
ご返信ありがとうございます。
whisper_device = cuda_16 の設定で無事音声認識させることができました。

なお、当方の環境では oscserver.py の 20行目で指定されている 9001 番ポートでは bind に失敗したため、9002 に変更することで対応しました。
当該ポートも指定可能とできるように設定項目に追加したほうがよいかもしれません。

`server = osc_server.ThreadingOSCUDPServer( ("127.0.0.1", 9002), dispatcher)`

**Comment by tyapa0** [comment]
>当該ポートも指定可能とできるように設定項目に追加したほうがよいかもしれません。
次回更新時に本変更も入れたいと思います。ありがとうございます。

**Comment by tyapa0** [comment]
> 当該ポートも指定可能とできるように設定項目に追加したほうがよいかもしれません。 

こちらも次回更新時に変更いたします。ご指摘ありがとうございます。
