### ISSUE TITLE
run.bat 実行後、使用するデバイス番号を入力すると FigureCanvasAgg エラーが発生

### ISSUE THREAD

**Issue by Accelan** [tyapa0/YukariWhisper#5]
お世話になっております。

Windows10 にて YukariWhisper 0.1.0、python 3.12.4 環境をクリーンインストール後
setup.bat 実行までは問題ありませんでしたが run.bat 実行すると、添付画像のエラー発生により
クライアントが強制終了します。

エラー内容より、グラフ表示系のライブラリが当方環境に不足しているのが原因ではないかと推測しておりますが
本件どのように対処すべきがご教示いただけないでしょうか。

![2024-06-13 21_55_06-Window](https://github.com/tyapa0/YukariWhisper/assets/40535024/4f656579-6055-4679-8dbe-b2f7dacf5c6f)

**Comment by tyapa0** [comment]
ご報告ありがとうございます。
ちょうど数時間前に使用しているnumpyライブラリの2.0が正式リリースされて、他のライブラリとの互換性が切れてphyon界隈が阿鼻叫喚していたところでした。  
数日前からRC版がリリースされており、インストールするとライブラリとの不整合が生じていたのだと思います。  
  
numpyを1.26.4に固定化する措置を行いました。古いフォルダは捨てて0.1.1を落としてsetup.batを実行してみてください。

**Comment by Accelan** [comment]
ご返信ありがとうございます。

0.1.1 新規インストールでも現象解消されなかったのですが、Python 3.12.4 や C:\Users\xxxx\.cache\huggingface\hub 以下の関連フォルダ等の削除を含めた
完全アンインストール後の再インストールにて、うまく動作できました。

関係なかったかもしれませんが、エラーが発生したときの Python 3.12.4 インストール時の
オプション機能選択で tcl/tk and IDLE 等を選択しなかったことが原因かもしれません。

今回はサポートいただきありがとうございました。
本 Issue をクローズさせていただきます。
